# -*- coding: utf-8 -*-
"""memory-garden-imgcaption-v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12ihcn-knF4rOAPJhXp2hGx6kaZap6BSE
"""

!pip install -q transformers accelerate bitsandbytes torch gtts --upgrade

import torch
from PIL import Image
from transformers import AutoModelForCausalLM, AutoModelForVision2Seq, AutoTokenizer, AutoProcessor

### This code is running on Google Colab T4 GPU

"""#### Qwen 2.5 for Image Caption"""

qwen_model_id = "Qwen/Qwen2.5-VL-7B-Instruct"

qwen_model = AutoModelForVision2Seq.from_pretrained(
    qwen_model_id,
    dtype=torch.float16,
    device_map="auto"
)

qwen_tokenizer = AutoTokenizer.from_pretrained(qwen_model_id)
qwen_processor = AutoProcessor.from_pretrained(qwen_model_id)

long_prompt = """
You are a compassionate storyteller. Using the attached photo, craft a 120–180 word micro‑story intended for an older adult and their family. The story should gently evoke memories, spark warm conversation, and support emotional well‑being.

Guidelines:
- Focus on mood, place, season, and relationships; avoid listing objects.
- Weave in 2–3 sensory details (sounds, scents, textures, light).
- Use warm, respectful language and short, vivid sentences.
- Avoid definitive claims about names, ages, or locations. Use gentle, tentative phrasing (perhaps, it seems, maybe).
- If people appear, emphasize connection and small rituals rather than appearance.
- Be inclusive and avoid stereotypes; balance nostalgia with quiet hope.
- If text is clearly legible in the image, you may thoughtfully incorporate it.
- If the scene is ambiguous, lean into universal themes (family, gatherings, journeys, everyday moments).

Output:
- 1–2 paragraphs of story.

Variants (pick one voice if you want to steer style):
- Voice A (third‑person close): Tell the story from a gentle narrator’s view.
- Voice B (first‑person elder): Write as if an older adult is recalling the moment in the photo.
- Voice C (second person): Address a loved one directly, with tenderness and gratitude.

Examples of style knobs you can add:
- Tone: warm and hopeful; lightly bittersweet; playful nostalgia.
- Era cues: hint at a decade only if strongly suggested by the image.
- Cultural touch: include respectful, non‑stereotyped details only if clearly present.

"""

short_prompt = """Write a 120–180 word micro‑story inspired by this photo for an older adult and their family. Describe the photo honestly, write the story to evoke gentle reminiscence and well‑being. Use warm, simple language, 2–3 sensory details, and avoid object lists. Use tentative phrasing for uncertain facts. Emphasize connection and small rituals."""

# Both long and short prompt works well. Use long one to generate story with variants (different perspective), use short one to generate clean and short story.
# I also tried two outputs of generating 1. 1–2 paragraphs of story 2. Then add “Conversation starters:” followed by two open‑ended, gentle questions that invite sharing (e.g., “What songs did you hear at gatherings like this?”).
# However, generating two open-ended questions that invite sharing (to echo with our proposal of sparking meaningful family conversation) did not work well (sometimes it is off topic or too general) so I removed it

def generate_story_qwen(image_path, prompt=short_prompt):
    image = Image.open(image_path).convert("RGB")

    messages = [
        {"role": "user", "content": [
            {"type": "image"},
            {"type": "text", "text": prompt}
        ]}
    ]

    text_prompt = qwen_processor.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    inputs = qwen_processor(text=[text_prompt], images=[image], return_tensors="pt").to("cuda")

    output_ids = qwen_model.generate(**inputs, max_new_tokens=300)

    generated_text = qwen_tokenizer.decode(
        output_ids[0][inputs["input_ids"].shape[1]:],
        skip_special_tokens=True
    )

    return generated_text.strip()

image_path = "example_photo/img_1.jpg" # should later replace with input
# three examples for testing ["img_1.jpg", "img_2.jpg", "img_3.png"]
image_story = generate_story_qwen(image_path)
### usually takes about 2 mins to generate the result on T4 GPU

print(image_story)

"""#### Translate from English to Chinese"""

from transformers import M2M100ForConditionalGeneration, M2M100Tokenizer

model_name = "facebook/m2m100_418M"
tokenizer = M2M100Tokenizer.from_pretrained(model_name)
model = M2M100ForConditionalGeneration.from_pretrained(model_name)

def translate_to_chinese(text):
    tokenizer.src_lang = "en"
    encoded = tokenizer(text, return_tensors="pt").to(model.device)
    generated_tokens = model.generate(**encoded, forced_bos_token_id=tokenizer.get_lang_id("zh"))
    return tokenizer.decode(generated_tokens[0], skip_special_tokens=True)

cantonese_text = translate_to_chinese(image_story)
print("Translated text:", cantonese_text)

